# Generated by Django 4.1.4 on 2023-02-02 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Homepage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasettext',
            name='rating',
            field=models.FloatField(default=0),
        ),
    ]
